### ISSUE TITLE
Task should be in Development on manual assignment

### ISSUE THREAD

**Issue by kenorb** [CodeMillApp/support#21]
I've unassigned person from the task (57eae5a7bf57f00003412f89), then assigned back the same person, the task is now in _Open Tasks_. I think Codemill should recognise the change and whenever task has been assigned to somebody (or same person), should be moved to _in Development_ section.

**Comment by CodeMillApp** [comment]
By 

> assigned back

you mean you did it via the GitHub UI? I guess it can be confusing: CodeMill wasn't been to be aware of those actions. The assumption was that since the client states the price, assignment can only be done explicitly by the developer, by clicking the `Grab It` button in the app. It then uses the GitHub API to assign the developer to the GH issue, just for convenience, but it doesn't go the other way around.

Practically, there it still no way in CodeMill for a client to assign a developer, only for a developer to "get themselves assigned to a task".

**Comment by kenorb** [comment]
@CodeMillApp Yes, I did it via GitHub UI. So first unassignment of task via Codemill (we can assume this was by mistake, as I wanted to test something), then the task become _Open_, then I wanted to fix the issue and assigned back to the same person via GitHub UI. I would expect that assignment is in sync between Codemill and GitHub, but if it's not going other way around, that's fine.

**Comment by CodeMillApp** [comment]
Actually I realized that there should be a way for a client to not assign dev maybe, but at least to send a task to a specific single or group of devs, and not to the entire user base. This way, if you have some devs you're used to work with and prefer to send them the task, it will server you better.
